### ISSUE TITLE
When used as a CMake dependency the build process stalls

### ISSUE THREAD

**Issue by dabadab** [andreacasalino/Minimal-Socket#26]
When using the library as a CMake dependency as described in the documentation the build process stalls as it also builds and runs all the example programs and the TCP server/client example does not exit.

**Comment by andreacasalino** [comment]
Thank you for using this library.

You are perfectly right. To solve the issue you can avoid to compile the samples when fetching, by doing this:
``` cmake
include(FetchContent)
set(BUILD_MinimalCppSocket_SAMPLES OFF CACHE BOOL "" FORCE) # you don't want the samples in this case
FetchContent_Declare(
min_sock
GIT_REPOSITORY https://github.com/andreacasalino/Minimal-Socket
GIT_TAG        master
)
FetchContent_MakeAvailable(min_sock)
```

I have changed the ReadMe:
https://github.com/andreacasalino/Minimal-Socket/commit/3908ba52211f39fb15538d923d975ee56e0b3fc0

Let me know if you have any other kind of problems.
