### ISSUE TITLE
Further problems when using as a CMake dependency

### ISSUE THREAD

**Issue by dabadab** [andreacasalino/Minimal-Socket#28]
Elaborating further on the usage as a CMake dependency, consider a simple project.

CMakeLists.txt:

```
project(test)
cmake_minimum_required(VERSION 3.11)
include(FetchContent)
set(CMAKE_CXX_STANDARD 20)

add_executable(test test.cpp)


# add Minimal-Socket

include(FetchContent)
set(BUILD_MinimalCppSocket_SAMPLES OFF CACHE BOOL "" FORCE) # you don't want the samples in this case
FetchContent_Declare(
	min_sock
	GIT_REPOSITORY https://github.com/andreacasalino/Minimal-Socket
	GIT_TAG        master
)
FetchContent_MakeAvailable(min_sock)

target_link_libraries(${TARGET_NAME}
	MinimalSocket
)
```

test.cpp:

```
#include <MinimalSocket/udp/UdpSocket.h>

int main()
{
    MinimalSocket::udp::UdpBinded udp_socket(1234, MinimalSocket::AddressFamily::IP_V4);
    
    return 0;
}
```

When trying to compile this two issues will come up:

1. the #include does not find the header files
2. (after fixing 1) the library is not linked to the executable so the linking fails with errors like `undefined reference to 'vtable for MinimalSocket::udp::UdpBinded'`

I realise that this may be "CMake 101 for dumbies" material but we dumbies still need some support :)

**Comment by andreacasalino** [comment]
TARGET_NAME is the generic name that was used in the read me to refer to the actual target that needs to consume MinimalSocket :). Therefore, the cmake code in your case should be this one:
``` cmake
target_link_libraries(test
	MinimalSocket
)
```

Then, if you are linking to another library, call it foo_lib, you may want to public link:
``` cmake
target_link_libraries(foo_lib PUBLIC
	MinimalSocket
)
```

I will leave this issue open until all problems will be sorted :)
