### ISSUE TITLE
Please add a LICENSE

### ISSUE THREAD

**Issue by coolbreeze413** [andreacasalino/Minimal-Socket#34]
Hi, we are looking to use this code in our projects, and it would be really helpful if you could add a license to clarify the usage.

Thanks!

**Comment by andreacasalino** [comment]
First of all thank you very much for your interest in this library.

I have added a GNU license:
80fe910192c64e24f35cea1d8988ff1b2c8af9ad

Please feel free to report any issue that you may have using this library and will do my best to address them as soon as possible.

Lastly, if this library is about to be used by someone else, ask them to leave a star too.

Thanks again

**Comment by andreacasalino** [comment]
Lincense added
