### ISSUE TITLE
Not able to run under VS2022

### ISSUE THREAD

**Issue by TuxxuT** [andreacasalino/Minimal-Socket#36]
Hi Andrea,

today I am trying to compile and run the examples of the tcp server <-> client applications (CMake based within VS2022).
Unfortunatly it fails and I don´t know why?

My build steps were:
1. I downloaded and unzipped the package "Minimal-Socket-v.2.0.zip".
2. Then I imported the whole CMake project in VS2022.
3. I think the generally build process was okay, because the MinimalSocket.lib was generated successfully.
4. Start one of the applications (TcpClient.exe, TcpServer.exe) fails with some error messages (see the screenshots).

![error2](https://github.com/andreacasalino/Minimal-Socket/assets/128478014/4ee06f8c-5efe-4503-9326-0a098b3c9f7d)

![error3](https://github.com/andreacasalino/Minimal-Socket/assets/128478014/4057d256-1f0f-4818-9be9-131f5aa553c9)

![error](https://github.com/andreacasalino/Minimal-Socket/assets/128478014/8458e62b-5362-4e1a-8cb2-a829ff43d601)

It would be great if you could take a look at it.

Thanks in advance!

**Comment by andreacasalino** [comment]
Hi,

Thanks for the interest in this library.

All samples are custom cmake target. However, I have recently discovered an issue in visual studio for this particular target. Therefore I created  [this PR](https://github.com/andreacasalino/Minimal-Socket/pull/37) to solve the issue.

Anyway, I am not sure that is the problem in your case. What do you mean by importing in VisualStudio the cmake project? Normally you should create the project from cmake (or the cmake GUI). This will generate for you the .sln representing the VisualStudio project. So everything should start in cmake and not VisualStudio.

Please try the new master version ([v.2.1](https://github.com/andreacasalino/Minimal-Socket/releases/tag/v.2.1)) configure the project like above suggested.
If that will not work we'll see what to do.

Let me know,
Andrea

**Comment by andreacasalino** [comment]
I assume the issue was solved ... happy to re-open if not
