### ISSUE TITLE
Document example for receiving/sending bytes?

### ISSUE THREAD

**Issue by MShields1986** [andreacasalino/Minimal-Socket#47]
Hello,
Many thanks for the library, I've been using it in projects for a while now.

I might be being a bit dense here, in the README.md you say that it is possible to receive and send bytes but I can't see an example of it in the docs and haven't been able to get it to work. It looks like I need to use the BufferView struct but I've failed to do so correctly.

Could you either point me to an example or maybe add one for this to the docs?

Specifically for my use case I'm creating a TCP server and looking to receive bytes from an external client.

**Comment by andreacasalino** [comment]
Hi,
thanks for the interest in this library!

the easiest way to receive something is to just specify the max lenght (call it L) of the message you want to receive. Then, blocking socket will absorb the caller, till L bytes are received or less if a termination character was sent.
Your tcp server would look something like this:
```cpp
#include <MinimalSocket/tcp/TcpServer.h>

int main() {
    MinimalSocket::Port port = 54321;
    // create a blocking server that binds the above port
    MinimalSocket::tcp::TcpServer<true> acceptor{ port };
    acceptor.open(); // blocking

    // accept one client (without loss of generality, indeed the same sever
    // can keep accept client till the acceptor socket is open)
    auto connected_client = acceptor.acceptNewClient(); // blocking

    // keep wait for request and respond to that client with an echo for example
    size_t max_request_size = 1000;
    while (true) {
        std::string request = connected_client.receive(max_request_size);
        if(request.empty()) {
            // connection was closed on the client side
            break;
        }

        // response will be at most max_request_size long
        std::string response = request; // here is just an echo for the purpose of the example
        connected_client.send(response); // notice that here the number of bytes to send is deduced by the size of the passed string
    }

    return EXIT_SUCCESS;
}
```
if you don't want the result to be stored on a string and then copied from there, you can use a generic buffer allocated by you somewhere and then pass a BufferView: specify as buffer your buffer and its lenght in buffer_size. This implies, that the socket will try to read at most buffer_size bytes and put the content of the received message into the passed BufferView::buffer.

[TcpServer.cpp](https://github.com/andreacasalino/Minimal-Socket/blob/master/samples/tcp/TcpServer.cpp) is doing something similar to the above sample of code. As you can see, any accepted client will be passed to a utility function named MinimalSocket::samples::respond (see [Respond.h](https://github.com/andreacasalino/Minimal-Socket/blob/master/samples/utils/Respond.h)), that will keep call receive on the passed socket to get the next message sent by the client (result is stored in a string as in the above example).

As soon as I have time, I will try to improve (probably by simplyfing) the proposed examples and README.md

Let me know if this helped you and don't hesitate to ask for more clarifications,
Andrea

**Comment by MShields1986** [comment]
Hello and thanks for the detailed and fast response!

I'm OK with setting up the receive, it was just accessing the underlying bytes rather than the returned string that I was struggling with.

When I looked through [Receiver.h](https://github.com/andreacasalino/Minimal-Socket/blob/master/src/header/MinimalSocket/core/Receiver.h) I saw an option to provide a BufferView type and thought that might be the preffered way to get to a buffer of bytes rather than a string returned from a receive. If this is the case it would be good to see how to use the BufferView struct as I've struggled.

For now I think I can get there using memcpy but it'd be nicer to not have to do the copy and just fill the buffer directly if this is possible?
```cpp
std::string request = connected_client.receive(max_request_size);
char buffer[request.size()];
std::memcpy(&buffer, request.c_str(), request.size());
std::cout << (short)*buffer << std::endl;
```

**Comment by andreacasalino** [comment]
So the BufferView is a non owning view of a buffer. Such buffer should have been pre allocated somewhere or can be a subportion of a bigger buffer. 
It is conceptually the same of a std::string_view. 

You want to pass a BufferView when you want the received message to be written in an already allocated buffer, with no need of extra copy. Therefore, exactly the scenario you were describing.

On the other hand, when you don't need the message to be allocated in a specific place of the memory, it is more easy to just receive it in a string.

Creating a BufferView is easy: just specify the pointer to the beginning of the buffer and its length. So in your case you would do something like this:
```cpp
  static constexpr std::size_t max_request_size = 500;
  char buffer[max_request_size];
  MinimalSocket::BufferView view{&buffer[0], max_request_size};
  size_t received_bytes =
      client.receive(view); // received_bytes will contain the number of bytes
                            // actually received and written into the buffer,
                            // from the specified starting point
```

**Comment by MShields1986** [comment]
Thanks for this, works well.
